export const FETCH_BASESTATION_START = "FETCH_BASESTATION_START"
export const FETCH_BASESTATION_SUCCESS = "FETCH_BASESTATION_SUCCESS"
export const FETCH_BASESTATION_FAILURE = "FETCH_BASESTATION_FAILURE"