export const FETCH_TOTALRUNS_START = "FETCH_TOTALRUNS_START"
export const FETCH_TOTALRUNS_SUCCESS = "FETCH_TOTALRUNS_SUCCESS"
export const FETCH_TOTALRUNS_FAILURE = "FETCH_TOTALRUNS_FAILURE"
export const SET_SELECTED_RUNS = "SET_SELECTED_RUNS"