export const FETCH_PTUID_START = "FETCH_PTUID_START"
export const FETCH_PTUID_SUCCESS = "FETCH_PTUID_SUCCESS"
export const FETCH_PTUID_FAILURE = "FETCH_PTUID_FAILURE"
export const SET_SELECTED_PTU = "SET_SELECTED_PTU"