export const FETCH_MANUFACTURE_START = "FETCH_MANUFACTURE_START"
export const FETCH_MANUFACTURE_SUCCESS = "FETCH_MANUFACTURE_SUCCESS"
export const FETCH_MANUFACTURE_FAILURE = "FETCH_MANUFACTURE_FAILURE"